/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DashBoard;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author USUARIO
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setLocationRelativeTo(this);
    }
    
    private void showPanel(JPanel p){
        p.setSize(600, 510);
        p.setLocation(0, 0);
        Bg.removeAll();
        Bg.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        Bg.revalidate();
        Bg.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cervezaBtn = new javax.swing.JPanel();
        cervezaTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        coctelesBtn = new javax.swing.JPanel();
        coctelesTxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vinosBtn = new javax.swing.JPanel();
        vinosTxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        destiladosBtn = new javax.swing.JPanel();
        destiladosTxt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        micheladasBtn = new javax.swing.JPanel();
        micheladasTxt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        noalcoholBtn = new javax.swing.JPanel();
        noalcoholTxt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Bg = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 550));

        bg2.setBackground(new java.awt.Color(85, 85, 85));
        bg2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 45, 45));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cervezaBtn.setBackground(new java.awt.Color(45, 45, 45));
        cervezaBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cervezaTxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        cervezaTxt.setForeground(new java.awt.Color(255, 255, 255));
        cervezaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cervezaTxt.setText("Cerveza");
        cervezaTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cervezaTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cervezaTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cervezaTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cervezaTxtMouseExited(evt);
            }
        });
        cervezaBtn.add(cervezaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cerveza.png"))); // NOI18N
        cervezaBtn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel1.add(cervezaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        coctelesBtn.setBackground(new java.awt.Color(45, 45, 45));
        coctelesBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coctelesTxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        coctelesTxt.setForeground(new java.awt.Color(255, 255, 255));
        coctelesTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coctelesTxt.setText("Cocteles");
        coctelesTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        coctelesTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coctelesTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                coctelesTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                coctelesTxtMouseExited(evt);
            }
        });
        coctelesBtn.add(coctelesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coctel.png"))); // NOI18N
        coctelesBtn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel1.add(coctelesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 60));

        vinosBtn.setBackground(new java.awt.Color(45, 45, 45));
        vinosBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vinosTxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        vinosTxt.setForeground(new java.awt.Color(255, 255, 255));
        vinosTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vinosTxt.setText("Vinos");
        vinosTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vinosTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vinosTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vinosTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vinosTxtMouseExited(evt);
            }
        });
        vinosBtn.add(vinosTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vino.png"))); // NOI18N
        vinosBtn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel1.add(vinosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, 60));

        destiladosBtn.setBackground(new java.awt.Color(45, 45, 45));
        destiladosBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        destiladosTxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        destiladosTxt.setForeground(new java.awt.Color(255, 255, 255));
        destiladosTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        destiladosTxt.setText("Destilados");
        destiladosTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        destiladosTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                destiladosTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                destiladosTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                destiladosTxtMouseExited(evt);
            }
        });
        destiladosBtn.add(destiladosTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/botella.png"))); // NOI18N
        destiladosBtn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel1.add(destiladosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 60));

        micheladasBtn.setBackground(new java.awt.Color(45, 45, 45));
        micheladasBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        micheladasTxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        micheladasTxt.setForeground(new java.awt.Color(255, 255, 255));
        micheladasTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        micheladasTxt.setText("Micheladas");
        micheladasTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        micheladasTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                micheladasTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                micheladasTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                micheladasTxtMouseExited(evt);
            }
        });
        micheladasBtn.add(micheladasTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/michelada.png"))); // NOI18N
        micheladasBtn.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel1.add(micheladasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 200, 60));

        noalcoholBtn.setBackground(new java.awt.Color(45, 45, 45));
        noalcoholBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noalcoholTxt.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        noalcoholTxt.setForeground(new java.awt.Color(255, 255, 255));
        noalcoholTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noalcoholTxt.setText("Sin alcohol");
        noalcoholTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        noalcoholTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noalcoholTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noalcoholTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noalcoholTxtMouseExited(evt);
            }
        });
        noalcoholBtn.add(noalcoholTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lata-de-refresco.png"))); // NOI18N
        noalcoholBtn.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel1.add(noalcoholBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 60));

        bg2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 510));

        jPanel2.setBackground(new java.awt.Color(45, 45, 45));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("HUBSON");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 800, 40));

        bg2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        Bg.setBackground(new java.awt.Color(85, 85, 85));
        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Goudy Old Style", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Bienvenido a HUBSON");
        Bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 600, 80));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bginicio.jpg"))); // NOI18N
        Bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-410, 0, 1010, 510));

        bg2.add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 600, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cervezaTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cervezaTxtMouseEntered
        cervezaBtn.setBackground(new Color(50,50,50));
    }//GEN-LAST:event_cervezaTxtMouseEntered

    private void cervezaTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cervezaTxtMouseExited
        cervezaBtn.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_cervezaTxtMouseExited

    private void coctelesTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coctelesTxtMouseEntered
        coctelesBtn.setBackground(new Color(50,50,50));
    }//GEN-LAST:event_coctelesTxtMouseEntered

    private void coctelesTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coctelesTxtMouseExited
        coctelesBtn.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_coctelesTxtMouseExited

    private void vinosTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vinosTxtMouseEntered
        vinosBtn.setBackground(new Color(50,50,50));
    }//GEN-LAST:event_vinosTxtMouseEntered

    private void vinosTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vinosTxtMouseExited
        vinosBtn.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_vinosTxtMouseExited

    private void destiladosTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destiladosTxtMouseEntered
        destiladosBtn.setBackground(new Color(50,50,50));
    }//GEN-LAST:event_destiladosTxtMouseEntered

    private void destiladosTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destiladosTxtMouseExited
        destiladosBtn.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_destiladosTxtMouseExited

    private void micheladasTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_micheladasTxtMouseEntered
       micheladasBtn.setBackground(new Color(50,50,50));
    }//GEN-LAST:event_micheladasTxtMouseEntered

    private void micheladasTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_micheladasTxtMouseExited
        micheladasBtn.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_micheladasTxtMouseExited

    private void noalcoholTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noalcoholTxtMouseEntered
        noalcoholBtn.setBackground(new Color(50,50,50));
    }//GEN-LAST:event_noalcoholTxtMouseEntered

    private void noalcoholTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noalcoholTxtMouseExited
        noalcoholBtn.setBackground(new Color(45,45,45));
    }//GEN-LAST:event_noalcoholTxtMouseExited

    private void cervezaTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cervezaTxtMouseClicked
        cervezas b = new cervezas();
        showPanel(b.getFondo());
    }//GEN-LAST:event_cervezaTxtMouseClicked

    private void coctelesTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coctelesTxtMouseClicked
        cocteles b = new cocteles();
        showPanel(b.getFondo());
    }//GEN-LAST:event_coctelesTxtMouseClicked

    private void vinosTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vinosTxtMouseClicked
        vinos b = new vinos();
        showPanel(b.getFondo());
    }//GEN-LAST:event_vinosTxtMouseClicked

    private void destiladosTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_destiladosTxtMouseClicked
        destilados b = new destilados();
        showPanel(b.getFondo());
    }//GEN-LAST:event_destiladosTxtMouseClicked

    private void micheladasTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_micheladasTxtMouseClicked
        micheladas b = new micheladas();
        showPanel(b.getFondo());
    }//GEN-LAST:event_micheladasTxtMouseClicked

    private void noalcoholTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noalcoholTxtMouseClicked
        sinalcohol b = new sinalcohol();
        showPanel(b.getFondo());
    }//GEN-LAST:event_noalcoholTxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JPanel bg2;
    private javax.swing.JPanel cervezaBtn;
    private javax.swing.JLabel cervezaTxt;
    private javax.swing.JPanel coctelesBtn;
    private javax.swing.JLabel coctelesTxt;
    private javax.swing.JPanel destiladosBtn;
    private javax.swing.JLabel destiladosTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel micheladasBtn;
    private javax.swing.JLabel micheladasTxt;
    private javax.swing.JPanel noalcoholBtn;
    private javax.swing.JLabel noalcoholTxt;
    private javax.swing.JPanel vinosBtn;
    private javax.swing.JLabel vinosTxt;
    // End of variables declaration//GEN-END:variables

}
